# Generated by Django 2.0.1 on 2018-01-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='molbank',
            fields=[
                ('ID', models.IntegerField(default='9999', primary_key=True, serialize=False)),
                ('SMILES', models.CharField(default='abc', max_length=100)),
            ],
        ),
    ]
