# Generated by Django 2.0.1 on 2018-02-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molbank',
            name='SAMPLE_CODE',
            field=models.CharField(default='DUMMY_SAMPLE_CODE', max_length=20),
        ),
        migrations.AlterField(
            model_name='molbank',
            name='ID',
            field=models.CharField(default='DUMMY_ID', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='molbank',
            name='SMILES',
            field=models.CharField(default='DUMMY_SMILES', max_length=150),
        ),
    ]
