# Generated by Django 2.0.1 on 2018-02-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molbank', '0003_all_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_products',
        ),
    ]
